// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Phishing_Platform_Midterm.Context;

#nullable disable

namespace Phishing_Platform_Midterm.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240114131041_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Phishing_Platform_Midterm.Entities.Phishingtemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Templatemail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("templatemail");

                    b.HasKey("Id")
                        .HasName("phishingtemplate_pkey");

                    b.ToTable("phishingtemplate", (string)null);
                });

            modelBuilder.Entity("Phishing_Platform_Midterm.Entities.Sentemail", b =>
                {
                    b.Property<int>("Emailid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("emailid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Emailid"));

                    b.Property<DateTime?>("Clickedat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("clickedat");

                    b.Property<bool?>("Isclicked")
                        .HasColumnType("boolean")
                        .HasColumnName("isclicked");

                    b.Property<DateTime?>("Sentat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sentat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Targetid")
                        .HasColumnType("integer")
                        .HasColumnName("targetid");

                    b.Property<int?>("Templateid")
                        .HasColumnType("integer")
                        .HasColumnName("templateid");

                    b.HasKey("Emailid")
                        .HasName("sentemail_pkey");

                    b.HasIndex("Targetid");

                    b.HasIndex("Templateid");

                    b.ToTable("sentemail", (string)null);
                });

            modelBuilder.Entity("Phishing_Platform_Midterm.Entities.Targetemail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Targetemail1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("targetemail");

                    b.HasKey("Id")
                        .HasName("targetemail_pkey");

                    b.ToTable("targetemail", (string)null);
                });

            modelBuilder.Entity("Phishing_Platform_Midterm.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<DateOnly?>("RegistrationDate")
                        .HasColumnType("date")
                        .HasColumnName("registrationDate");

                    b.Property<string>("Sourcepage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sourcepage");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Phishing_Platform_Midterm.Entities.Userinteraction", b =>
                {
                    b.Property<int>("Interactionid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("interactionid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Interactionid"));

                    b.Property<int?>("Emailid")
                        .HasColumnType("integer")
                        .HasColumnName("emailid");

                    b.Property<string>("Interactiondetail")
                        .HasColumnType("text")
                        .HasColumnName("interactiondetail");

                    b.Property<DateTime?>("Interactiontime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("interactiontime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Interactiontype")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("interactiontype");

                    b.Property<int?>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Interactionid")
                        .HasName("userinteraction_pkey");

                    b.HasIndex("Emailid");

                    b.HasIndex("Userid");

                    b.ToTable("userinteraction", (string)null);
                });

            modelBuilder.Entity("Phishing_Platform_Midterm.Entities.Sentemail", b =>
                {
                    b.HasOne("Phishing_Platform_Midterm.Entities.Targetemail", "Target")
                        .WithMany("Sentemails")
                        .HasForeignKey("Targetid")
                        .HasConstraintName("sentemail_targetid_fkey");

                    b.HasOne("Phishing_Platform_Midterm.Entities.Phishingtemplate", "Template")
                        .WithMany("Sentemails")
                        .HasForeignKey("Templateid")
                        .HasConstraintName("sentemail_templateid_fkey");

                    b.Navigation("Target");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Phishing_Platform_Midterm.Entities.Userinteraction", b =>
                {
                    b.HasOne("Phishing_Platform_Midterm.Entities.Sentemail", "Email")
                        .WithMany("Userinteractions")
                        .HasForeignKey("Emailid")
                        .HasConstraintName("userinteraction_emailid_fkey");

                    b.HasOne("Phishing_Platform_Midterm.Entities.User", "User")
                        .WithMany("Userinteractions")
                        .HasForeignKey("Userid")
                        .HasConstraintName("userinteraction_userid_fkey");

                    b.Navigation("Email");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Phishing_Platform_Midterm.Entities.Phishingtemplate", b =>
                {
                    b.Navigation("Sentemails");
                });

            modelBuilder.Entity("Phishing_Platform_Midterm.Entities.Sentemail", b =>
                {
                    b.Navigation("Userinteractions");
                });

            modelBuilder.Entity("Phishing_Platform_Midterm.Entities.Targetemail", b =>
                {
                    b.Navigation("Sentemails");
                });

            modelBuilder.Entity("Phishing_Platform_Midterm.Entities.User", b =>
                {
                    b.Navigation("Userinteractions");
                });
#pragma warning restore 612, 618
        }
    }
}
